server:
  port: 8080
  forward-headers-strategy: framework

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/seller_center}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html